name: 'fish-shop/install-plugin-manager'
description: 'A GitHub action for installing a fish shell plugin manager'
branding:
  icon: 'arrow-down'
  color: 'green'
inputs:
  plugin-manager:
    description: 'The name of the fish shell plugin manager to install'
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        set -gx TERM xterm-256color
        switch ${{ inputs.plugin-manager }}
            case fisher
                if test (type -q fisher) $status -ne 0
                    curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source
                    fisher install jorgebucaran/fisher
                else
                    echo "Plugin manager already installed: fisher"
                end
            case oh-my-fish
                if test (type -q omf) $status -ne 0
                    curl -L https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install > omf-install
                    chmod u+x omf-install
                    ./omf-install -y --noninteractive
                    rm -f omf-install
                else
                    echo "Plugin manager already installed: oh-my-fish"
                end
            case plug.fish
                if test (type -q plug) $status -ne 0
                    curl -L https://l0c.cc/plug.fish | plugins=https://github.com/kidonng/plug.fish source
                    printf "%s\n" \
                        "set plugins https://github.com/kidonng/plug.fish" \
                        "source $__fish_user_data_dir/plugins/plug.fish/conf.d/plugin_load.fish" \
                        >> ~/.config/fish/config.fish
                else
                    echo "Plugin manager already installed: plug.fish"
                end
            case '*'
                echo "Unrecognised plugin manager: '${{ inputs.plugin-manager }}'" >&2; and exit 1
        end
      shell: fish {0}
